version: '3.9'

services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql

  minio:
    image: quay.io/minio/minio:latest
    entrypoint: sh
    command: -c 'mkdir -p /data/test && /usr/bin/minio server /data'
    ports:
      - 9000:9000
